* Project: garden-mower

*garden-mower* is a simple css preprocessor that merges specific selector attributes from a css document, and outputs data that can be digested by [[https://github.com/noprompt/garden]].

* Motivation

I want to use tailwindcss, but I want to keep my tooling within clojure. I need to be able to
create custom class selectors which combine the attributes of specified tailwindcss classes.

I want to convert the following, where the keyword arguments passed to *mower/attributes* designate tailwindcss css classes:

#+BEGIN_SRC clojure
[[:.card-container (mower/attributes css :.flex :.mx-auto :.flex-col :.sm:flex-row)]
 [:.card-outer (mower/attributes css :.max-w-sm :.w-full :.sm:max-w-full :.lg:flex :.mb-1 :.mx-auto :.sm:mx-1)]]
#+END_SRC

into the equivalent of the following:

#+BEGIN_SRC css
.card-container {
  display: flex;
  margin-left: auto;
  margin-right: auto;
  flex-direction: column;
}

@media (min-width: 640px) {
  .card-container {
    flex-direction: row;
  }
}

.card-outer {
  max-width: 24rem;
  width: 100%;
}

@media (min-width: 640px) {
  .card-outer {
    max-width: 100%;
  }
}

@media (min-width: 1024px) {
  .card-outer {
    display: flex;
  }
}

.card-outer {
  margin-bottom: 0.25rem;
  margin-left: auto;
  margin-right: auto;
}

@media (min-width: 640px) {
  .card-outer {
    margin-left: 0.25rem;
    margin-right: 0.25rem;
  }
}
#+END_SRC

* Examples

- tailwindcss [[examples/tailwind]]

* Usage

*garden-mower.core/attributes* walks a css document and extracts the attributes that match the selector(s), and converts them into a form that can be digested by [[https://github.com/noprompt/garden]].

Currently, the fetched selectors must be simple single elements, but the result of *garden-mower.core/attributes* can be embedded anywhere.

Because *garden* supports nested media queries (great!), media queries of the selectors are preserved. The following example demonstrates this:

#+BEGIN_SRC clojure
  (let [css "
    @media (min-width: 640px) {
      .blue   { color: rgba(0,0,255,1); }
    }
    .bg-red { background-color: rgba(255,0,0,1); }"]
    (garden.core/css [[:.btn (mower/attributes css :.blue :.bg-red)]
                      [:.btn-red (mower/attributes css :.bg-red)]]))
#+END_SRC

Produces:

#+BEGIN_SRC css
@media (min-width: 640px) {

  .btn {
    color: rgba(0, 0, 255, 1);
  }

}

.btn {
  background-color: rgba(255, 0, 0, 1);
}

.btn-red {
  background-color: rgba(255, 0, 0, 1);
}
#+END_SRC

* License

https://opensource.org/licenses/MIT
