name: On-push workflow

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: populates /github/workspace inside the docker container
        uses: actions/checkout@v2

      - name: uses the action.yml and Dockerfile found under .github/actions/test
        uses: ./.github/actions/test